server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html index.htm;

    location / {
        # Tenta carregar o arquivo; se não achar (como em rotas do Angular), joga pro index.html
        try_files $uri $uri/ /index.html;
    }

    # Cache opcional de imagens e fontes para carregar mais rápido
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}
